version: 2

# --------------------------------
# common : base
# --------------------------------

base: &base
  docker:
  - image: circleci/php:7.1-node-browsers

# --------------------------------
# common : steps
# --------------------------------

install_svn: &install_svn
  name: 'Install SVN'
  command: |
    sudo apt-get install subversion
    mkdir wordpress-plugins
    cd wordpress-plugins
    svn checkout https://plugins.svn.wordpress.org/woocommerce-user-shortcode/

# --------------------------------
# common : jobs
# --------------------------------
jobs:
  pull-request-job:
    <<: *base
    steps:
    - checkout
    - run: *install_svn


# --------------------------------
# workflows
# --------------------------------

workflows:
  version: 2
  build:
    jobs:
    - pull-request-job:
        filters:
          branches:
            only: circleci


