version: 2

# --------------------------------
# common : base
# --------------------------------

base: &base
  docker:
  - image: circleci/php:7.1-node-browsers

# --------------------------------
# common : steps
# --------------------------------

install_svn: &install_svn
  name: 'Run tests'
  command: |
    apt-get install subversion

# --------------------------------
# common : jobs
# --------------------------------
jobs:
  pull-request-job:
    <<: *base
    steps:
    - checkout
    - run: *install_svn

# --------------------------------
# workflows
# --------------------------------

workflows:
  version: 2
  build:
    jobs:
    - pull-request-job:
        filters:
          branches:
            - circleci
